version: "3.7"
services:
    app:
        build:
            args:
                user: shop-user
                uid: 1000
            context: ..
            dockerfile: docker-compose/Dockerfile
        image: shop-backend
        container_name: shop-backend
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ../:/var/www
        networks:
            - shop-network

    nginx:
        image: nginx:alpine
        container_name: shop-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ../:/var/www
            - ./nginx:/etc/nginx/conf.d/
        networks:
            - shop-network

#    migrate:
#        image: php:8.2-cli
#        volumes:
#            - ./:/var/www
#        working_dir: /var/www/
#        depends_on:
#            - app
#        command: sh -c "composer insta"
networks:
    shop-network:
        driver: bridge
